name: SMS Gamer UPS Monitor
version: "latest"
slug: sms_gamer_ups_monitor
description: Monitora e controla o nobreak SMS Gamer via MQTT para Home Assistant, com suporte a comandos e configurações avançadas.
url: https://github.com/Eduwico/SMS_nobreak_gamer
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
# startup: before
boot: auto
ports: {}
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyACM0
  - /dev/serial/by-id/*
options:
  serial_port: /dev/ttyUSB0
  poll_interval: 10
  baud_rate: 2400
  timeout: 3
  mqtt_broker: core-mqtt
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
schema:
  serial_port: str
  poll_interval: int(1,300 )
  baud_rate: int(1200,115200)
  timeout: int(1,30)
  mqtt_broker: str
  mqtt_port: int(1,65535)
  mqtt_username: str
  mqtt_password: password
image: ghcr.io/eduwico/sms_gamer_ups_monitor-{arch}
