"""" # .github/workflows/build-and-push.yaml
name: Build and Push Docker image

on:
  push:
    tags:
      - 'v*'  
      # Executa ao push de tags como v1.1.5, v1.2.0 etc.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: |
          ghcr.io/eduwico/sms_gamer_ups_monitor:latest
          ghcr.io/eduwico/sms_gamer_ups_monitor:${{ github.ref_name }}
"""
