---
name: SMS Gamer UPS Monitor
slug: sms_nobreak_serial
description: Monitora e controla o nobreak SMS Gamer via MQTT para Home Assistant, com suporte a comandos, sensores e configuração via Discovery. (EXPERIMENTAL)
version: "0.1"
url: https://github.com/du-costa/sms_nobreak_serial
arch:
  - aarch64
  - armv7
  - armhf
  - amd64

startup: services
boot: auto
host_network: false
uart: true
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_AQAZb135B02-if00-port0
  - /dev/serial/by-id/*
ports: {}
map: []
options:
  serial_port: /dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_AQAZb135B02-if00-port0
  poll_interval: 10
  baud_rate: 2400
  timeout: 3
  mqtt_broker: core-mqtt
  mqtt_port: 1883
  mqtt_username: mqtt
  mqtt_password: mqtt
schema:
  serial_port: str?
  poll_interval: int(1,300)
  baud_rate: int(1200,115200)
  timeout: int(1,30)
  mqtt_broker: str
  mqtt_port: int(1,65535)
  mqtt_username: str?
  mqtt_password: password?
image: ghcr.io/du-costa/sms_nobreak_serial-{arch}
